### stop 1
POST http://localhost:8010/shop/actuator/status/stop

### start 1
POST http://localhost:8010/shop/actuator/status/start

### stop 2
POST http://localhost:8011/shop/actuator/status/stop

### start 2
POST http://localhost:8011/shop/actuator/status/start