### get/detail
GET http://localhost:8011/shop/book/detail/1

### get/simple
GET http://localhost:8011/shop/book/simple/1006

### get/medium
GET http://localhost:8011/shop/book/medium/1

### get/pageable, all
GET http://localhost:8011/shop/books/all?page=0&size=20

### get/pageable, best
GET http://localhost:8011/shop/books/best?page=0&size=20

### get/pageable, category
GET http://localhost:8011/shop/books/category/420?page=0&size=20

### delete
DELETE http://localhost:8011/shop/book/delete/2
